services:
  create-package:
    image: ubuntu:latest
    working_dir: /app
    entrypoint: ["bash", "/app/create-package.sh"]
    environment:
      - NODE_ENV=development
    command: ["bash", "-c", "while true; do sleep 1000; done"]

  bats-tests:
    image: bats/bats:latest
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["bats", "/app/__tests__/*.bats"]